version: '2'
services:
    springboot:
        container_name: platform-interview
        build:
            context: platform-interview
            dockerfile: Dockerfile
        image: platform-interview:0.0.1-SNAPSHOT
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge
